[theme]
name = "enight"
desc = "tokyonight colors, rounding, nice and intensive blur, fast animations"
version = "0.69"
author = "end-4"
git = "https://github.com/end-4/dots-hyprland"
config = "hyprland.conf"
